language: java
jdk:
  - oraclejdk8
 
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install sshpass

after_success:
  - "sshpass -p 'y.KWpMP5@4;]Cfd%' scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q -r logfiles ubuntu@82.221.50.35:/usr/share/nginx/html/"
