language: java
sudo: false
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - sshpass

after_success:
  - "sshpass -p 'y.KWpMP5@4;]Cfd%' scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q -r build/reports ubuntu@82.221.50.35:/usr/share/nginx/html/logs/reports/"
  - "sshpass -p 'y.KWpMP5@4;]Cfd%' scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q -r build/jacoco/reports ubuntu@82.221.50.35:/usr/share/nginx/html/logs/jacoco/"
after_failure:
  - "sshpass -p 'y.KWpMP5@4;]Cfd%' scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q -r build/reports ubuntu@82.221.50.35:/usr/share/nginx/html/logs/reports/"
  - "sshpass -p 'y.KWpMP5@4;]Cfd%' scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q -r build/jacoco/reports ubuntu@82.221.50.35:/usr/share/nginx/html/logs/jacoco/"
  
