/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'steinn' at '10/25/15 5:54 PM' with Gradle 2.8
 *
 * @author steinn, @date 10/25/15 5:54 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
